# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    branches:
        include:
            - master
            - develop
            - releases/*

variables:
- group: DevDeploymentVarGroup

stages:
    - stage: 'Build'
      displayName: 'Build the backend REST api'
      jobs:
          - job: 'Build'
            displayName: 'Build job'
            pool:
                vmImage: '$(buildVmImage)'

            steps:
                - task: UseDotNet@2
                  inputs:
                    version: '5.0.x'
                    includePreviewVersions: true # Required for preview versions
                
                - task: DotNetCoreCLI@2
                  displayName: Restore
                  inputs:
                    command: 'restore'
                    projects: '**/*.csproj'
                    includeNuGetOrg: true

                - task: DotNetCoreCLI@2
                  displayName: Build
                  inputs:
                    command: build
                    projects: '**/*.csproj'
                    arguments: '--no-restore --configuration $(buildConfiguration)'

                - task: DotNetCoreCLI@2
                  displayName: Publish
                  inputs:
                    command: publish
                    publishWebProjects: false
                    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
                    zipAfterPublish: true

                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Artifact: drop'
                  condition: succeeded()

                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Artifact: drop'
                  inputs:
                      pathtoPublish: 'ArmTemplates'

    - stage: 'Deploy'
      displayName: 'Deploy the backend REST api'
      dependsOn: Build
      condition: and (succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
      jobs:
          - deployment: Deploy
            pool:
                vmImage: '$(deployVmImage)'
            environment: Development
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - download: current
                              artifact: drop

                            - task: AzureResourceManagerTemplateDeployment@3
                              displayName: Create a storage account for deployment artifacts
                              inputs:
                                deploymentScope: 'Resource Group'
                                azureResourceManagerConnection: '$(managedIdentityName)'
                                subscriptionId: '$(subscriptionId)'
                                action: 'Create Or Update Resource Group'
                                resourceGroupName: '$(resourceGroupName)'
                                location: '$(resourceGroupLocation)'
                                templateLocation: 'Linked artifact'
                                csmFile: '$(Pipeline.Workspace)/drop/infrastructure/storage/azuredeploy.json'
                                overrideParameters: -storageAccountName $(storageAccountName) -containerName $(storageContainerName)
                                deploymentMode: 'Incremental'
                                deploymentOutputs: 'armOutputs'

                            - task: AzureFileCopy@4
                              displayName: Copy deployment artifacts to the storage account
                              inputs:
                                sourcePath: '$(Pipeline.Workspace)/drop/infrastructure'
                                azureSubscription: $(managedIdentityName)
                                destination: AzureBlob
                                storage: $(storageAccountName)
                                containerName: $(storageContainerName)
                                cleanTargetBeforeCopy: true

                            - task: AzureResourceManagerTemplateDeployment@3
                              displayName: Deploy backend infrastructure
                              inputs:
                                deploymentScope: 'Resource Group'
                                azureResourceManagerConnection: '$(managedIdentityName)'
                                subscriptionId: '$(subscriptionId)'
                                action: 'Create Or Update Resource Group'
                                resourceGroupName: '$(resourceGroupName)'
                                location: '$(resourceGroupLocation)'
                                templateLocation: 'Linked artifact'
                                csmFile: '$(Pipeline.Workspace)/drop/azuredeploy.json'
                                csmParametersFile: '$(Pipeline.Workspace)/drop/azuredeploy.parameters.json'
                                overrideParameters: |
                                  -webAppDomain $(appName) 
                                  -apiSuffix $(apiSuffix) 
                                  -backendSuffix $(backendSuffix) 
                                  -apimSuffix $(apimSuffix) 
                                  -apimVersionPath $(apimVersionPath) 
                                  -apimDisplayName $(apimDisplayName) 
                                  -environment $(environment) 
                                  -sku $(appSku) 
                                  -dotnetVersion $(backendApiDotnetVersion) 
                                  -templatesStorageAccountName $(storageAccountName) 
                                  -templatesContainerName $(storageContainerName)
                                deploymentMode: 'Incremental'
                                deploymentOutputs: 'armOutputs'

                            - task: AzureWebApp@1
                              displayName: 'Deploy .net core 5 api to azure app service'
                              inputs:
                                  azureSubscription: '$(managedIdentityName)'
                                  appName: '$(appName)-$(backendSuffix)-$(apiSuffix)-$(environment)'
                                  appType: 'webApp'
                                  package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
