# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    branches:
        include:
            - master
            - develop
            - releases/*

variables:
- group: DevDeploymentVarGroup

stages:
    - stage: 'Build'
      displayName: 'Build the backend REST api'
      jobs:
          - job: 'Build'
            displayName: 'Build job'
            pool:
                vmImage: '$(buildVmImage)'

            steps:
                - task: UseDotNet@2
                  inputs:
                    version: '5.0.x'
                    includePreviewVersions: true # Required for preview versions
                
                - task: DotNetCoreCLI@2
                  displayName: Restore
                  inputs:
                    command: 'restore'
                    projects: '**/*.csproj'
                    includeNuGetOrg: true

                - task: DotNetCoreCLI@2
                  displayName: Build
                  inputs:
                    command: build
                    projects: '**/*.csproj'
                    arguments: '--configuration $(buildConfiguration)'

                - task: DotNetCoreCLI@2
                  displayName: Publish
                  inputs:
                    command: publish
                    publishWebProjects: True
                    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
                    zipAfterPublish: True

                - task: PublishBuildArtifacts@1
                  inputs:
                    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
                    artifactName: 'micolk-backend-api'
